### ISSUE TITLE
错误信息：Uncaught SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by crazyair** [qq645381995/beijingshishigongjiao#1]
https://sentry.io/48b35f825cb7/42fb0fa6d774/issues/266771425/

```
Stacktrace (最近的调用最先显示)

  at logException (/static/js/bundle.js:4141:2)
  at window.onerror (/static/js/bundle.js:4141:2)

错误信息：Uncaught SyntaxError: Unexpected token u in JSON at position 0
```

**Comment by crazyair** [comment]
dwdwdwd第五大道哇多我的

**Comment by crazyair** [comment]
12121
